# Generated by Django 4.1.2 on 2022-10-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcaja', models.IntegerField(max_length=25)),
                ('tipocaja', models.IntegerField(max_length=5)),
                ('hora_res', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado_per', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numturno', models.IntegerField(max_length=25)),
                ('hora_solicitud', models.TimeField()),
                ('estado_tur', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_caja_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.caja')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('prioritario', models.IntegerField(max_length=5)),
                ('tipo_atencion', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_turno_tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='id_personal_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.personal'),
        ),
    ]
