# Generated by Django 4.1.2 on 2022-10-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado_per', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('prioritario', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numturno', models.CharField(max_length=25)),
                ('estado_tur', models.IntegerField(max_length=5)),
                ('tipo_turno', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_user_tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.user')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcaja', models.IntegerField(max_length=25)),
                ('tipocaja', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_personal_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.personal')),
                ('id_turno_tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
        ),
    ]
